
# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory

# A version range to match for said mod loader - for regular FML @Mod it will be the FML version. This is currently 2.
loaderVersion="2" #mandatory

# The license for you mod. This is mandatory metadata and allows for easier comprehension of your redistributive properties.
license="MIT"

# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://github.com/Limoxd/Horse-Engine-Mod/issues" #optional

# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory

# The modid of the mod
modId="horse_engines" #mandatory

# The version number of the mod
version="1.0.0" #mandatory

# A display name for the mod
displayName="Horse Engines" #mandatory

# A URL to query for updates for this mod. See the JSON update specification https://docs.neoforged.net/docs/misc/updatechecker/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional

# A URL for the "homepage" for this mod, displayed in the mod UI
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional

#logoFile="examplemod.png" #optional

credits="LimoXD"

authors="LimoXD"

description='''
Feed oild to your horses to make them faster!!
'''

# The [[mixins]] block allows you to declare your mixin config to FML so that it gets loaded.
#[[mixins]]
#config="${mod_id}.mixins.json"

# The [[accessTransformers]] block allows you to declare where your AT file is.
# If this block is omitted, a fallback attempt will be made to load an AT from META-INF/accesstransformer.cfg
#[[accessTransformers]]
#file="META-INF/accesstransformer.cfg"

[[dependencies.horse_engines]] #optional
    modId="neoforge" #mandatory
    type="required" #mandatory
    versionRange="[${neo_version},)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.horse_engines]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.horse_engines]]
    modId = "oritech"
    type = "optional"
    versionRange = "[1.2.10, )"
    ordering="NONE"
    side = "BOTH"

[[dependencies.horse_engines]]
    modId = "createdieselgenerators"
    type = "optional"
    versionRange = "[1.3.15, )"
    ordering="NONE"
    side = "BOTH"

[[dependencies.horse_engines]]
    modId = "tfmg"
    type = "optional"
    versionRange = "[1.2.0, )"
    ordering="NONE"
    side = "BOTH"
[[dependencies.horse_engines]]
    modId = "pneumaticcraft"
    type = "optional"
    versionRange = "[8.2.23, )"
    ordering="NONE"
    side = "BOTH"

#[features.${mod_id}]
#openGLVersion="[3.2,)"
